const gtwca = [
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:gsXAJv6AazMWZqtwT2gP_",
        command: "$USAC:ENTRY",
        mlpEntryId: 2,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:gsXAJv6AazMWZqtwT2gP_",
        teamName: "RS1",
        racelinkNumber: "218093",
        transponderNumber: "3158476",
        isTeam: true,
        vehicle: "Porsche GT3 R 992",
        manufacturer: "Porsche",
        number: "28",
        series: "FGTWCA",
        sponsors: "Porsche Naples, CBW Racing, Sabelt",
        class: "Pro",
        drivers: [
            {
                firstName: "Eric",
                middleName: null,
                lastName: "Filgueiras",
                tla: "FIL",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Silver",
                driverId: 1,
                isFirst: true,
            },
            {
                firstName: "Stevan",
                middleName: null,
                lastName: "McAleer",
                tla: "MCA",
                nationality: "SCO",
                licenseNationality: "USA",
                category: "Gold",
                driverId: 2,
                isFirst: false,
            },
        ],
        firstDriverIndex: null,
    },
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:GIW4ZNasZyUz-hs-6RgRD",
        command: "$USAC:ENTRY",
        mlpEntryId: 1,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:GIW4ZNasZyUz-hs-6RgRD",
        teamName: "Conquest Racing",
        racelinkNumber: "218045",
        transponderNumber: "15951331",
        isTeam: true,
        vehicle: "Ferrari 296 GT3",
        manufacturer: "Ferrari",
        number: "21",
        series: "FGTWCA",
        sponsors: "Corza Horizon",
        class: "Pro",
        drivers: [
            {
                firstName: "Manny",
                middleName: null,
                lastName: "Franco",
                tla: "FRA",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Silver",
                driverId: 1,
                isFirst: true,
            },
            {
                firstName: "Alessandro",
                middleName: null,
                lastName: "Balzan",
                tla: "BAL",
                nationality: "ITA",
                licenseNationality: "USA",
                category: "Gold",
                driverId: 2,
                isFirst: false,
            },
        ],
        firstDriverIndex: null,
    },
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:u5L7uRGXDu2KFdO0MnAo-",
        command: "$USAC:ENTRY",
        mlpEntryId: 3,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:u5L7uRGXDu2KFdO0MnAo-",
        teamName: "BimmerWorld",
        racelinkNumber: "218017",
        transponderNumber: "10013918",
        isTeam: true,
        vehicle: "BMW M4 GT3",
        manufacturer: "BMW",
        number: "94",
        series: "FGTWCA",
        sponsors:
            "TAC Energy, Ozium, Cazo de Oro, Pretzilla, PFC Brakes, and Red Line Oil",
        class: "Pro",
        drivers: [
            {
                firstName: "Chandler",
                middleName: null,
                lastName: "Hull",
                tla: "HUL",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Silver",
                driverId: 4,
                isFirst: true,
            },
            {
                firstName: "Bill",
                middleName: null,
                lastName: "Auberlen",
                tla: "AUB",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Gold",
                driverId: 1,
                isFirst: false,
            },
        ],
        firstDriverIndex: null,
    },
];

const gtam = [
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:gsXAJv6AazMWZqtwT2gP_",
        command: "$USAC:ENTRY",
        mlpEntryId: 2,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:gsXAJv6AazMWZqtwT2gP_",
        teamName: "TKO Motorsports",
        racelinkNumber: "218093",
        transponderNumber: "3158476",
        isTeam: true,
        vehicle: "Mercedes-AMG GT3",
        manufacturer: "Mercedes",
        number: "101",
        series: "GT America",
        sponsors: "",
        class: "SRO3",
        drivers: [
            {
                firstName: "Memo",
                middleName: null,
                lastName: "Gidley",
                tla: "GID",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Bronze",
                driverId: 1,
                isFirst: true,
            },
        ],
        firstDriverIndex: null,
    },
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:GIW4ZNasZyUz-hs-6RgRD",
        command: "$USAC:ENTRY",
        mlpEntryId: 1,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:GIW4ZNasZyUz-hs-6RgRD",
        teamName: "CRP Racing",
        racelinkNumber: "218045",
        transponderNumber: "15951331",
        isTeam: true,
        vehicle: "Mercedes-AMG GT3",
        manufacturer: "Mercedes",
        number: "27",
        series: "GT America",
        sponsors: "",
        class: "SRO3",
        drivers: [
            {
                firstName: "Jason",
                middleName: null,
                lastName: "Daskalos",
                tla: "DAS",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Bronze",
                driverId: 1,
                isFirst: true,
            },
        ],
        firstDriverIndex: null,
    },
    {
        _level: 0,
        _key: "$USAC:ENTRY|entries:events-lJKQh5JmkIuKl8rnnFAqm:u5L7uRGXDu2KFdO0MnAo-",
        command: "$USAC:ENTRY",
        mlpEntryId: 3,
        id: "entries:events-lJKQh5JmkIuKl8rnnFAqm:u5L7uRGXDu2KFdO0MnAo-",
        teamName: "Wright Motorsports",
        racelinkNumber: "218017",
        transponderNumber: "10013918",
        isTeam: true,
        vehicle: "Porsche 992 R GT3",
        manufacturer: "Porsche",
        number: "120",
        series: "GT America",
        sponsors: "",
        class: "SRO3",
        drivers: [
            {
                firstName: "Adam",
                middleName: null,
                lastName: "Adelson",
                tla: "ADE",
                nationality: "USA",
                licenseNationality: "USA",
                category: "Bronze",
                driverId: 4,
                isFirst: true,
            },
        ],
        firstDriverIndex: null,
    },
];

export { gtwca, gtam };
