# fly.toml app configuration file generated for podium-socket on 2023-09-01T13:49:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "podium-socket"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
