name: Fly Deploy
on:
    push:
        branches:
            - main
jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set Working Directory
              run: cd $GITHUB_WORKSPACE
            - name: Install Dependencies and Run Tests
              run: |
                  npm install mocha chai
                  npx mocha src/Socket_Test/test
    deploy:
        name: Deploy app
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Deploy if Tests Passed
              if: success()
              run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
